### ISSUE TITLE
Undefined symbols: boost::thread::hardware_concurrency()

### ISSUE THREAD

**Issue by ryandesign** [stendardo/shenidam#1]
Hi, I'm trying to compile shenidam (latest git revision f68da2ac7f876742643e0d6cbba20315891c809a) on OS X Snow Leopard, using MacPorts (trying to [make a portfile](https://trac.macports.org/ticket/33891) in fact). During the cmake configure phase, it says:

```
-- Looking for _init in boost_thread
-- Looking for _init in boost_thread - not found
-- Looking for C++ include boost/thread.hpp
-- Looking for C++ include boost/thread.hpp - found
CMake Warning at CMakeLists.txt:83 (message):
  No boost::thread library available.
```

The build fails with:

```
Undefined symbols:
  "boost::thread::hardware_concurrency()", referenced from:
      parse_options(int, char**)in shenidam_main.cpp.o
ld: symbol(s) not found
```

**Comment by stendardo** [comment]
Sorry I missed this issue. Just replace boost::thread::hardware_concurrency() by the number of cores in your system. I really need to find a lightweight cross-platform way of doing that.

**Comment by ryandesign** [comment]
Should this be the number of cores on the system building the software, or the system that will ultimately run it? They might not be the same system.

**Comment by stendardo** [comment]
It should be the number of cores on the target system.

**Comment by ryandesign** [comment]
By "target system" do you mean the system that will ultimately run the software? If so, then it's unknown at build time what that value would be. We might build the software on a system with X cores and later want to run it on a system with Y cores.

**Comment by stendardo** [comment]
Yes. It's just a temporary workaround. If you know of a cross-platform method to determine the number of cores at runtime which does not depend on any heavyweight library, let me know.

## Nabil

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

ryandesign notifications@github.com wrote:

By "target system" do you mean the system that will ultimately run the software? If so, then it's unknown at build time what that value would be. We might build the software on a system with X cores and later want to run it on a system with Y cores.

**Comment by ryandesign** [comment]
shenidam 1.0 builds fine on OS X.
