### ISSUE TITLE
Audio is not cropped to the length of the video. Videos are not trimmed.

### ISSUE THREAD

**Issue by abramhindle** [stendardo/shenidam#5]
Hi, with a 96khz wavfile as the base file and MOV files from a Canon T2i shenidam was working great at finding the start of the match, but the resulting files tended to contain all of the audio til the next match or the end of the file. This was also true for flac.

```
hindle1@piggy:/media/hindle1/MyMedia/Videos/20160123-arts-birthday$ file MVI_1557.MOV agape-raygun-experiment--and--don-ross-and-skruntskrunt.WAV 
MVI_1557.MOV:                                                ISO Media, Apple QuickTime movie, Apple QuickTime (.MOV/QT)
agape-raygun-experiment--and--don-ross-and-skruntskrunt.WAV: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 24 bit, stereo 96000 Hz
```

I had to recut the files:

```
#!/bin/bash
BASE=$1
shift
echo Shenidamming it
shenidam-av -b $BASE -o "{dir}/uncut.{base}.match.mkv" $*
for file in $*
do
        BASE2=`echo $file | sed -e 's/\..*$//' | sed -e 's/^.*\///'`
        UNCUT="uncut.${BASE2}.match.mkv"
        F2="${BASE2}.match.mkv"
        DURATION=`avprobe $file -show_format  -v quiet | fgrep duration | awk -F= '{print $2}'`
        echo $file to $F2 with duration $DURATION
        avconv -i $file -t $DURATION -vcodec copy -acodec copy $F2
done
rm uncut.*.match.mkv
```

So I would run:

```
shendammit agape-raygun-experiment--and--don-ross-and-skruntskrunt.WAV MVI_1557.MOV MVI_1558.MOV etc. 
```

and each file would have a lot of audio data in it. So I would have to use that script to cut the video file.

I tried providing the -shortest flag to avconv but no luck. Have you seen this behaviour before?

**Comment by stendardo** [comment]
Thank you for the bug report. I have fixed it in 'master'.

**Comment by abramhindle** [comment]
Oh awesome! I'll check it immediately. Thanks for the great software, it seems to work far better than kdenlive and other matchers I have tried.

**Comment by abramhindle** [comment]
Alright it did work. Thanks again.
