### ISSUE TITLE
shenidam.org is down

### ISSUE THREAD

**Issue by Joeboy** [stendardo/shenidam#9]
Hi. Just went to look at the website (which as far as I know is the place to find instructions for shenidam / shenidam-av / qshenidam) and it's showing a Webfaction "site not configured" error.

Would be good if instructions were also available in the git repo in case this happens. Cheers!

**Comment by stendardo** [comment]
I am reorganizing the site, so it's normal.

Nabil Stendardo

**Comment by Joeboy** [comment]
Great, glad to hear this is due to activity not inactivity!
